name: lightmeter
description: A new Flutter project.
publish_to: "none"
version: 0.3.0+5

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  camera: 0.10.0+4
  exif: 3.1.2
  dynamic_color: 1.5.4
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.1
  flutter_localizations:
    sdk: flutter
  intl: 0.17.0
  intl_utils: 2.8.1
  material_color_utilities: 0.1.5
  package_info_plus: 3.0.2
  permission_handler: 10.2.0
  provider: 6.0.4
  shared_preferences: 2.0.15
  url_launcher: 6.1.8
  vibration: 1.7.6

dev_dependencies:
  google_fonts: 3.0.1
  flutter_launcher_icons: 0.11.0
  flutter_lints: 2.0.0
  flutter_native_splash: 2.2.16
  test: 1.22.2

dependency_overrides:
  test_api: 0.4.12

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_icons:
  image_path_android: "assets/launcher_icon_circle.png"
  android: "launcher_icon"
  adaptive_icon_background: "#fafafa"
  image_path_ios: "assets/launcher_icon_square.png"
  ios: true
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_intl:
  enabled: true
