name: lightmeter
description: Lightmeter app inspired by Material 3 design system.
publish_to: "none"
version: 0.16.0+45

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  app_settings: 4.2.0
  bloc_concurrency: 0.2.2
  camera: 0.10.5+2
  clipboard: 0.1.3
  dynamic_color: 1.6.6
  exif: 3.1.4
  firebase_analytics: 10.6.2
  firebase_core: 2.20.0
  firebase_crashlytics: 3.4.2
  firebase_remote_config: 4.3.2
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.3
  flutter_localizations:
    sdk: flutter
  intl: 0.18.0
  intl_utils: 2.8.2
  light_sensor: 3.0.0
  m3_lightmeter_iap:
    git:
      url: "https://github.com/vodemn/m3_lightmeter_iap"
      ref: v0.7.1
  m3_lightmeter_resources:
    git:
      url: "https://github.com/vodemn/m3_lightmeter_resources"
      ref: main
  material_color_utilities: 0.2.0
  package_info_plus: 4.0.2
  permission_handler: 10.4.3
  platform: 3.1.0
  shared_preferences: 2.2.0
  url_launcher: 6.1.12
  uuid: 3.0.7
  vibration: 1.8.1

dev_dependencies:
  bloc_test: 9.1.3
  build_runner: 2.4.6
  flutter_driver:
    sdk: flutter
  flutter_launcher_icons: 0.11.0
  flutter_native_splash: 2.3.5
  flutter_test:
    sdk: flutter
  google_fonts: 3.0.1
  integration_test:
    sdk: flutter
  lint: 2.1.2
  mocktail: 0.3.0
  test: 1.24.1

flutter:
  uses-material-design: true
  assets:
    - assets/camera_stub_image.jpg

flutter_intl:
  enabled: true
