name: lightmeter
description: Lightmeter app inspired by Material 3 design system.
publish_to: "none"
version: 1.1.0+60

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: "3.24.5"

dependencies:
  app_settings: 5.1.1
  auto_size_text: 3.0.0
  bloc_concurrency: 0.3.0
  camera: 0.11.0+2
  clipboard: 0.1.3
  collection: any
  dynamic_color: 1.7.0
  exif: 3.3.0
  firebase_analytics: 11.4.0
  firebase_core: 3.10.0
  firebase_crashlytics: 4.3.0
  firebase_remote_config: 5.3.0
  flutter:
    sdk: flutter
  flutter_bloc: 9.0.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: 2.4.4
  geolocator: 13.0.1
  intl: 0.19.0
  intl_utils: 2.8.7
  light_sensor: 3.0.1
  m3_lightmeter_iap:
    git:
      url: "https://github.com/vodemn/m3_lightmeter_iap"
      ref: v2.1.3
  m3_lightmeter_resources:
    git:
      url: "https://github.com/vodemn/m3_lightmeter_resources"
      ref: v2.1.0
  material_color_utilities: 0.12.0
  package_info_plus: 8.1.3
  permission_handler: 11.3.1
  platform: 3.1.5
  shared_preferences: 2.3.5
  url_launcher:
  url_launcher_ios: 6.3.2
  uuid: 4.5.1
  vibration: 2.0.1
  map_launcher: 3.2.0

dev_dependencies:
  args: 2.6.0
  bloc_test: 10.0.0
  build_runner: 2.4.13
  flutter_test:
    sdk: flutter
  golden_toolkit: 0.15.0
  google_fonts: 6.2.1
  image: 4.3.0
  integration_test:
    sdk: flutter
  lint: 2.3.0
  logging: 1.3.0
  meta: 1.15.0
  mocktail: 1.0.4
  test: 1.25.7

dependency_overrides:
  geolocator_android: 4.6.1
  m3_lightmeter_iap:
    path: /Users/vodemn/Documents/GitHub/Vodemn/m3_lightmeter_iap
  m3_lightmeter_resources:
    path: /Users/vodemn/Documents/GitHub/Vodemn/m3_lightmeter_resources
  material_color_utilities: 0.11.1

flutter:
  uses-material-design: true
  assets:
    - assets/camera_stub_image.jpg
    - assets/release_notes/

flutter_intl:
  enabled: true
